artifact base
tarikbir/Secret-of-Meowun pull request #2
Opened 2022-02-02 12:07 UTC by recep-sen

artifact base architecture

2022-02-03 07:25 UTC, tarikbir commented on Assets/_Scripts/Artifact/Artifact.cs
> +    public enum Trigger
bunu genelleştirirsek daha süper olur aslında buraya özel olmasın, kartlarda da kullanılacak :) event classı yaparsak ona taşıyabiliriz common yapıda

2022-02-03 07:26 UTC, tarikbir commented on Assets/_Scripts/Artifact/ArtifactMethods.cs
> +    public void SpringBoots()
Burda da yapılan işe göre metod yazarsak belki 2 yerden farklı değerlerle trigger etmemiz gerekecek bir metodu artifactlere bağlamamış oluruz, proxy yapmaya gerek olmaz :)

2022-02-03 07:45 UTC, tarikbir requested changes

2022-02-03 07:45 UTC, tarikbir commented on Assets/_Scripts/Artifact/ArtifactMethods.cs
> +    {
Hatta direkt öyle yapalım ya değiştir bunları öyle onaylayalım

2022-02-03 11:01 UTC, recep-sen commented
tamamdır değişiklikleri halledip öyle mergeleriz

2022-02-03 19:34 UTC, tarikbir requested changes

2022-02-03 19:34 UTC, tarikbir commented on Assets/_Scripts/Artifact/Artifact.cs
> +    public enum WhenToCall
No.

2022-02-03 19:34 UTC, tarikbir commented on Assets/_Scripts/Artifact/ArtifactMethods.cs
> +    public void JumpCount(int jumpCount)
SetJumpCount()

2022-02-06 12:46 UTC, tarikbir approved these changes

2022-02-06 13:14 UTC, merged